### ISSUE TITLE
Where i can found C# code examples?

### ISSUE THREAD

**Issue by fatkulamri** [ukandrewc/Webview2.Winforms.DOM#13]
Hi All,

Where i can found C# code examples?

**Comment by ukandrewc** [comment]
There aren't any at present, but you can easily use an online converter to create C# from the VB.

**Comment by larrygmoody** [comment]
Will you be creating any C# web scraping examples? The available methods do not display with intellisense.

**Comment by ukandrewc** [comment]
Sorry, I'm not planning to create any C# examples. The properties should show in Intellisense, I don't know why they wouldn't show. Can you see WVBrowser in the Object Browser?

**Comment by ukandrewc** [comment]
That's good then. I have often seen Intellisense not working correctly, where I know a function exists, but it's not in the list.
