### ISSUE TITLE
Need for basic example

### ISSUE THREAD

**Issue by genesislubrigas** [ukandrewc/Webview2.Winforms.DOM#14]
I have seen the code sample but somehow it is not the basic one and does not show the use of DOM access, how we go over the control without knowing the documentation of the controls.

I am hoping that you can kindly provide us this basic example and the documentation as well.

Thanks.

**Comment by ukandrewc** [comment]
There is no documentation yet, but the DOM is accessed in exactly the same way as the WebBrowser control.
There is an example in TabForm.DOMDocumentCompleted.
