### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by knoami** [ukandrewc/Webview2.Winforms.DOM#15]
I am constantly getting this error:

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=WVBrowser
>   StackTrace:
>    at Aimco.WV2.WVAutoFill.HideAutoSelect()

I am using a very simple code to navigate to google.com !! What is the problem?

**Comment by ukandrewc** [comment]
Sorry about that, because MS are now going to implement autofill, I have removed that code.
I'm just doing some code changes, then will release an update, hopefully before Monday.

**Comment by knoami** [comment]
Okay, thanks for your efforts 😃

**Comment by ukandrewc** [comment]
Updated the code now, but please see readme for breaking changes.

**Comment by knoami** [comment]
I just checked the sample code, but I got the following error when I run the **Border Form Test** project:

> System.NullReferenceException
> HResult=0x80004003
> Message=Object reference not set to an instance of an object.
> Source=WVBrowser
> StackTrace:
> at Aimco.WV2.WVNavStrip.SetSecureIcon()

**Comment by knoami** [comment]
There's another error here also:

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Single Form Test
>   StackTrace:
>    at Single_Form_Test.TestFrm.Body_DOMEventAsync(String Type, WVEvent e) in ..\WVBrowser\Webview2.Winforms.DOM-master\Webview2.Winforms.DOM-master\WVBrowser Samples\Single Form Test\TestFrm.vb:line 22

**Comment by knoami** [comment]
One more error here:

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=WVBrowser
>   StackTrace:
>    at Aimco.WV2.WVTabButton.TabButton_Disposed(Object sender, EventArgs e)

**Comment by knoami** [comment]
Here also:

> System.Reflection.TargetInvocationException
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=mscorlib
>   StackTrace:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
>    at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
>    at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
>    at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
>    at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
>    at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
>    at Single_Form_Test.My.MyApplication.Main(String[] Args) in :line 81
> 
>   This exception was originally thrown at this call stack:
>     Single_Form_Test.TestFrm.Body_DOMEventAsync(String, Aimco.WV2.WVEvent) in TestFrm.vb
>     Aimco.WV2.WVElement.EventHost_DOMEventAsync(string, Aimco.WV2.WVEvent)
>     Aimco.WV2.WVEventHost._Closure$__14-0._Lambda$__0()
> 
> Inner Exception 1:
> NullReferenceException: Object reference not set to an instance of an object.
> 
>

**Comment by ukandrewc** [comment]
Change content of **TestFrm>Body_DOMEventAsync** to this:
```
If Type = "mouseover" Then
	Dim Elm = WvBrowser1.Document.ElementFromPoint(New Point(e.PageX, e.PageY))
	If Elm IsNot Nothing Then
		ElemLabel.Text = Elm.TagName
	End If
End If

```

**Comment by ukandrewc** [comment]
I've trapped those errors now, so if you download wvbrowser.dll again, should be OK.

**Comment by knoami** [comment]
> I've trapped those errors now, so if you download [wvbrowser.dll](https://github.com/ukandrewc/Webview2.Winforms.DOM/blob/master/WVBrowser%20Samples/Include/WVBrowser.dll) again, should be OK.

Okay thanks, I will check and revert back

**Comment by knoami** [comment]
it looks good now, thank you very much 😊

**Comment by knoami** [comment]
![image](https://user-images.githubusercontent.com/14849330/114438288-38993680-9bd0-11eb-8f30-fad4bf189f98.png)

by the way, do you know how to interrupt these messages?

**Comment by ukandrewc** [comment]
I do, and you to can read the docs here ;-): https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionrequestedeventargs?view=webview2-dotnet-1.0.824-prerelease

**Comment by knoami** [comment]
> I do, and you to can read the docs here ;-): https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionrequestedeventargs?view=webview2-dotnet-1.0.824-prerelease

Thanks, yes I found the same on google. thank you very much 😊

**Comment by knoami** [comment]
> I do, and you to can read the docs here ;-): https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionrequestedeventargs?view=webview2-dotnet-1.0.824-prerelease

but this solution doesn't help with the "**Download Multiple Files**" message !! 

![image](https://user-images.githubusercontent.com/14849330/114447117-b2ceb880-9bda-11eb-98da-3f02d93730ea.png)

I tried to use the **ScriptDialogOpening** but didn't work. Do you know any solution for this case?

**Comment by ukandrewc** [comment]
We'll have to wait for the files API from MS, for that. It's part of the reason I haven't finished a lot of this control, waiting for MS to finish their various functions.
