### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by GunArm** [ukandrewc/Webview2.Winforms.DOM#18]
Sorry if I'm asking a stupid question, but where is the code?  The repo seems to just be samples, a readme, and prebuilt dlls.  Is this closed source?

**Comment by ukandrewc** [comment]
Not a stupid question, but yes it is closed source.

**Comment by GunArm** [comment]
Thanks for the quick response.  FYI I was pointed here by this https://github.com/MicrosoftEdge/WebView2Feedback/issues/667
