### ISSUE TITLE
$ in ID or other Attributes causes problems

### ISSUE THREAD

**Issue by igotbass** [ukandrewc/Webview2.Winforms.DOM#2]
id="X$PageBody$MainContent$ctl00$UserName"
I believe the $ in the ID or other Attrib causes problems

Tried with both the getfromid and QuerySelector and QueryAll with just basic //input with no $ in query and it wont return the element 

Oh and in console removed $ from ID and it works fine, tested.

**Comment by ukandrewc** [comment]
Hmm, that's odd, the query string is just passed through, but will have a look

**Comment by igotbass** [comment]
> Hmm, that's odd, the query string is just passed through, but will have a look

By the way thank you for doing this project, esp this early on in the game, it will help so many people, your work is invaluable and I sincerely appreciate it.

**Comment by ukandrewc** [comment]
Not seeing that here.
Evaluate (XPath) will work, but QuerySelector won't $ is used for EndsWith 

`<input id="$test">`

Works
`document.evaluate("//input[@id='$test']",document).iterateNext()`

Doesn't
`document.querySelector("input#$test")`

**'input#$test' is not a valid selector**
You can see that in DevTools console

**Comment by ukandrewc** [comment]
> thank you for doing this project

No problem at all, it's been good fun
