### ISSUE TITLE
checkbox checked attribute

### ISSUE THREAD

**Issue by pjacko** [ukandrewc/Webview2.Winforms.DOM#20]
Hi Andrew, 
Thanks for your work.
Just a question, what is the best way to get the 'checked' attribute from a checkbox element?
Currently the WVHTMLElement.get_GetAttribute("checked") returns a blank.
regards
Paul Jackson

**Comment by ukandrewc** [comment]
Hi Paul

That is odd, I will have a look at why that is, but you can cast it to a `WVInput` and then you have a `.checked` property.

**Comment by ukandrewc** [comment]
That's the same in DevTools, it returns null for getAttribute on a checkbox.

I'm going to add a default property, that will work the same as the named ones, then you will be able to use `WVElement("checked")`

**Comment by ukandrewc** [comment]
I've already added it, you can do `WVElement("checked")`, now.

**Comment by pjacko** [comment]
thanks Andrew. I'll give it a whirl
