### ISSUE TITLE
A problem with CoreWebView2.DownloadStarting

### ISSUE THREAD

**Issue by knoami** [ukandrewc/Webview2.Winforms.DOM#21]
Hi,

I tried to use CoreWebView2.DownloadStarting in the new update but I got the following error:

```
System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Experimental2.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning ---> System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Experimental2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{84E547A6-2CF7-4966-A44E-3DD10BE69A7F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

   at Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2Experimental2()

   --- End of inner exception stack trace ---

   at Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2Experimental2()

   at Microsoft.Web.WebView2.Core.CoreWebView2.add_DownloadStarting(EventHandler`1 value)

```

It seems like there's a conflict somewhere but I don't know where. I am using WebView2 version 1.0.865.0.

Could you please help?

**Comment by ukandrewc** [comment]
Not sure, I'll see what happens here.

**Comment by ukandrewc** [comment]
It seems OK here, not done exhaustive testing, but changed download file name, and cancelled, both successful.

Check you are using that version WebView2, because I don't think this API is experimental in 1.0.865.0.

**Comment by knoami** [comment]
As per this page:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental2?view=webview2-1.0.865-prerelease&preserve-view=true#add_downloadstarting

It's experimental !!

The problem in my case happen when I use this code:

`AddHandler WV2.CoreWebView2.DownloadStarting, AddressOf Example_DownloadStarting`

**Comment by knoami** [comment]
This page also says it's experimental.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental2?view=webview2-1.0.865-prerelease

**Comment by ukandrewc** [comment]
Fair enough, but It's nothing to do with WVBrowser, it's between WebView2 and your code.

**Comment by knoami** [comment]
Yes, I know that. I just asked in case you know the solution.

Do you have a working sample code for DownloadStarting API?

**Comment by ukandrewc** [comment]
@knoami No. Other than to test for this, I haven't tried it yet. It didn't cause any errors.
