### ISSUE TITLE
WVBrowser.Document property changed to WVBrowser.document (?)

### ISSUE THREAD

**Issue by pjacko** [ukandrewc/Webview2.Winforms.DOM#22]
Hi Andrew,
I have just downloaded the latest zip file but noticed that the WVBrowser.Document property has changed to WVBrowser.document.
Just wondering for the reason? 
I can easily change my code, but just wondering if it was intentional?
thanks
Paul Jackson

**Comment by pjacko** [comment]
Andrew,
Just noticed it right across the board. New naming convention?

**Comment by ukandrewc** [comment]
@pjacko Yes, it was intentional, but understand it's a Marmite decision ;-)

I added a default property for WVNode, so you can access any property with text e.g. `MyElement("href")`

As the name needs to be the same as JS, it seemed logical to make everything else uniform.

**Comment by ukandrewc** [comment]
PS if you select all code in a document, press Tab, it will reformat it for you.

**Comment by pjacko** [comment]
👍Thanks Andrew
