### ISSUE TITLE
Change exiting JavaScript in Webview2 

### ISSUE THREAD

**Issue by knoami** [ukandrewc/Webview2.Winforms.DOM#23]
How  to change an existing Javascript in page loaded through WebView2 under .Net Winforms as I need to do some customizations.

The code that I am trying to change it during the runtime is:

` <script language="JavaScript" type="text/javascript">
           
             var mywindow;
             function logon() {
            	 
            
    	          if(document.forms['form1'].elements["USERNAME"].value=="){
    	            alert('Please enter your User name...');
    	            document.forms['form1'].elements["USERNAME"].focus();
    	            return paxReturn(false);
    	          }
    	          if(document.forms['form1'].elements["PASSWORD"].value=="){
    	            alert('Please enter your password...');
    	            document.forms['form1'].elements["PASSWORD"].focus();
    	            return paxReturn(false);
    	          }
              
              
              
          	  if (mywindow!=) {
           		showObjectWithSrvlt('CoderInfo','LoginServlet');
          	  }
          
              if((mywindow==)||(mywindow.closed)) {
                var prm ='toolbar=no,titlebar=no,directories=no,menubar=no,resizable=yes,scrollbars=yes,width=900,height=600,top=0,left=0';
                mywindow = window.open(",'Demo',prm);   
              }
               document.forms['form1'].target = 'Demo';
               try{
                  mywindow.resizeTo(screen.width,screen.height);
               }catch(e) {}
           
              
    		   if(typeof(JavaBridge) != "undefined" && JavaBridge) {
    		   
    		   	document.forms['form1'].elements["java-bridge"].value = "true"
    		   }      
               document.forms['form1'].submit();
               try{
                  mywindow.focus();
               }catch(e) {}
               document.forms['form1'].elements["USERNAME"].value=";
               document.forms['form1'].elements["PASSWORD"].value=";
               disableButtonContent(this,false);
            }
             
             function logInControl(){   
            	 
            	 
            		 logon();
            	 
        
        	}
             
    </script>
`

**Comment by ukandrewc** [comment]
There are a few things that aren't supported yet, such as `document.forms` and `window.open` and `window.resizeTo`, but I will add those.

**Comment by ukandrewc** [comment]
I've added the additional functionality to WVWindow, so you can achieve this in .Net now.
