### ISSUE TITLE
Error on latest sample

### ISSUE THREAD

**Issue by pjacko** [ukandrewc/Webview2.Winforms.DOM#25]
Andrew,
I attempted to run the latest sample from git and zip and received the following error:

> Could not load file or assembly 'WebView2JS Helper, Version=1.0.0.0, Culture=neutral, Public KeyToken=null' or one of its dependecies.

![image](https://user-images.githubusercontent.com/25918236/120434258-93c0fb80-c3bf-11eb-8c73-8670d5f30319.png)

any ideas?

**Comment by ukandrewc** [comment]
Fixed that now, had started to include [JSHelper](https://github.com/ukandrewc/WebView2.Winforms.JSHelper) as native extensions, but left the reference to original DLL.

Fixed now.

**Comment by pjacko** [comment]
The @checked still comes up in C# with the WVBrowser 0.0.865.2 version.
However 'checked' is a reserved word in C#, which could be the reason.

```
#region Assembly WVBrowser, Version=0.0.865.2, Culture=neutral, PublicKeyToken=null
// C:\temp\webview2\Webview2.Winforms.DOM-master\WVBrowser Samples\Include\WVBrowser.dll
#endregion

namespace Aimco.WV2 {
    public class WVInput : WVHTMLElement {
        public WVInput(WVBrowser NewBrowser, ulong Id);

...

        public string formAction { get; set; }
        public bool @checked { get; set; }
...        
        public void setSelectionRange(int Start, int Finish, WVUtils.WVSelectionDirection SelectionDirection = WVUtils.WVSelectionDirection.none);
    }
}

```

**Comment by ukandrewc** [comment]
Yes, it seems that the @ prefix is added by .Net for C# only. In VB or C++ you just see **checked**, doesn't look like there is any way round it.
I've never worked extensively in C#, as I started .Net with VB, so I wasn't aware of that.
