### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by knoami** [ukandrewc/Webview2.Winforms.DOM#26]
Sometimes I am facing the following error: 

```
** Message: 
Object reference not set to an instance of an object.
-----------------------------------------------------------
** Source: 
WVBrowser
-----------------------------------------------------------
** Stack Trace:
   at Aimco.WV2.WVScriptHost.Browser_DOMDocumentComplete(Object sender)
   at Aimco.WV2.WVBrowser.DOMDocumentCompleteEventHandler.Invoke(Object sender)
   at Aimco.WV2.WVBrowser.RaiseDOMEvent(String EventName)
   at Aimco.WV2.WVScriptHost._Closure$__47-0._Lambda$__0()
-----------------------------------------------------------
```

It's random, what's the reason?

**Comment by knoami** [comment]
@ukandrewc, Any feedback on this error?

**Comment by ukandrewc** [comment]
What code do you have inside DOMDocumentComplete?

**Comment by knoami** [comment]
I don't use it at all, this is why I am asking about the reason.

It happens from time to time, not always.

**Comment by ukandrewc** [comment]
This could have been an issue in an earlier version, but the current version is checked for null references, so it doesn't make any sense.

The only reference used in raising DOMDocumentComplete is sender (WVBrowser), so unless it has been unloaded but not disposed, it shouldn't be happening.

**Comment by knoami** [comment]
It still happening !!

Today I was browsing a site and when I clicked on **Go Back** button to move to the previous page, I got this error message.

**Comment by ukandrewc** [comment]
If you can let me have a way to reproduce this, that would be good.

I've just spent 10 minutes navigating, going back, forward, stopping & refreshing without any issue.
