### ISSUE TITLE
AppendChild

### ISSUE THREAD

**Issue by evanhsu179** [ukandrewc/Webview2.Winforms.DOM#27]
Excuse me
My code is as follows

**Dim injectScript As WVHTMLElement = EDGE1.document.createElement("SCRIPT")
injectScript.textContent = "JSCode"
EDGE1.document.getElementsByTagName("HEAD")(0).append(injectScript) '<-- error**

How do i get under the HEAD element
Insert the injectScript element
thank you very much

**Comment by knoami** [comment]
Try the following code:

`EDGE1.CoreWebView2.ExecuteScriptAsync("var Scrp = document.createElement(""script""); Scrp.setAttribute('language', 'JavaScript'); Scrp.type = 'text/javascript'; var tsc1 = document.createTextNode('" & NewCode & "'); Scrp.appendChild(tsc1); var currentFrm = document.getElementsByTagName("HEAD"); document.body.insertBefore(Scrp, currentFrm.childNodes[0]);")`

**Comment by ukandrewc** [comment]
At the moment append isn't overloaded for WVNode, it only accepts string, so just use:

`Web.document.getElementsByTagName("head")(0).append("<script>alert()</script>")`

**Comment by evanhsu179** [comment]
Thanks for the above two answers
