### ISSUE TITLE
NavigationCompleted event not fired on Windows Server

### ISSUE THREAD

**Issue by knoami** [ukandrewc/Webview2.Winforms.DOM#28]
Why the Sample code works fine on Windows 10 but doesn't work on Windows Server 2012?

I traced the code, and I found that the **NavigationCompleted** event not fired on Windows Server, what's the reason?

[FormTest.zip](https://github.com/ukandrewc/Webview2.Winforms.DOM/files/6603126/FormTest.zip)

**Comment by ukandrewc** [comment]
Sorry, I don't know the answer to that. NavigationCompleted is a native WebView2 event, so you'd need to ask on the WebView2 forum.

**Comment by knoami** [comment]
Okay thanks
