### ISSUE TITLE
IFRAME Elements

### ISSUE THREAD

**Issue by igotbass** [ukandrewc/Webview2.Winforms.DOM#6]
Using get_Evaluate or similar does this library have the ability to access elements in an IFrame using some type of Xpath selector ??

**Comment by ukandrewc** [comment]
Yes, as normal: `window.frames[0].document.evaluate( "//input", window.frames[0].document.body)`

**Comment by igotbass** [comment]
> Yes, as normal: `window.frames[0].document.evaluate( "//input", window.frames[0].document.body)`
> 
> Or you can traverse from the top window: `document.evaluate( "//iframe//input", document)`

I apoligize I am not understanding, there is no such function as .evaluate that accepts 2 arguements ?
Sorry for the annoyance, I just have been stuck on this for a day now I would appreciate the direction ?

**Comment by ukandrewc** [comment]
Do you mean from javascript or .Net?

**Comment by igotbass** [comment]
WVElement Elle =  webView21.Document.get_Evaluate("xxx") or eimilar ?

In .net with your browser how do I get access to dom in iframe with a specific name ?

for example with OG Webbrowser control we were doing this not using xpath.

iterate over all of the frames until finding correct src of the frame and then accessing it via

webBrowser1.Document.Window.Frames[i].Document.GetElementById("rightContent").All)

How do i do the same thing with your browser?

I really appreciate your help.



for (int i = 0; i <= webBrowser1.Document.Window.Frames.Count; i++)
                            {
                                try
                                {
                                    if (webBrowser1.Document.Window.Frames[i].WindowFrameElement.GetAttribute("src") == "https://www.website.com/buy/")
                                    {
                                        bool DoneImporting = true;
                                        foreach (HtmlElement NextPage in webBrowser1.Document.Window.Frames[i].Document.GetElementById("rightContent").All)
                                        {
                                            if (NextPage.GetAttribute("className") == "next")
                                            {
                                                DoneImporting = false;
                                                NextPage.InvokeMember("click");
                                                break;
                                            }
                                        }
                                       
                                        break;
                                    }
                                }
                                catch
                                {
                                }
                            }

**Comment by ukandrewc** [comment]
You should be able to do the same with WVBrowser, but as yet I haven't added support for iframes.
It will be coming but it's a bit awkward to implement.

**Comment by igotbass** [comment]
> You should be able to do the same with WVBrowser, but as yet I haven't added support for iframes.
> It will be coming but it's a bit awkward to implement.

Ok with that being said, until its implemented with the current revision of WV Browser can u please give me a .net code example how to access an iFrame with the currently available methods in the WV Browser.

For example if I have an iFrame 

<iframe name="ifr_sas_eim_browser_Browser_0"  src="https://www.eim.com/buy/"></iframe>

How would i access this iframe by name and be able to use xpath expression to search for elements within that frame ?

With the get_Evaluate function or similar ????

**Comment by ukandrewc** [comment]
You can access the Iframe with `Browser.Document.Evaluate("//iframe[@name='ifr_sas_eim_browser_Browser_0']")`
But you can't get to the document, until there is an update.

**Comment by igotbass** [comment]
Ok thank you, Any idea when there will be an Update, I would be glad to donate if u have a patreon ??

**Comment by ukandrewc** [comment]
Updated that today, you can now use Evaluate from the Frames collection.

`Dim Elm = WVBrowser.Window.Frames(0).Document.Evaluate(...)`

You'll need to identify your iframe in the frames collection, as I haven't implemented Document on iframe element yet.

**Comment by ukandrewc** [comment]
Added IFrame support now.

Any elements that are IFrames will be returned as a WVIFrameElement class
