### ISSUE TITLE
Sync Version of ExecuteScriptAsync

### ISSUE THREAD

**Issue by igotbass** [ukandrewc/Webview2.Winforms.DOM#7]
Could you please post a  c# .net example of the Sync version of Execute Script Async, if possible.
Or how can I call ExecuteScriptAsync from a Sync Method ?

How to get the return string in a Sync Method ???

I appreciate the help again.

Thanks

**Comment by ukandrewc** [comment]
That's been added to the latest version:

```
'Async Execute
WVBrowser.Window.ExecuteAsync(...)
' Sync Execute with timeout
WVBrowser.Window.Execute(...)
'Sync Execute with no timeout e.g. for dialog calls
WVBrowser.Window.ExecuteSync(...)
```

**Comment by igotbass** [comment]
> WVBrowser.Window.ExecuteSync(...)

Perfect TY very much.
